### ISSUE TITLE
Possibility of making a direct stream without having to store the file previously (Server side)

### ISSUE THREAD

**Issue by 11ume** [tus/tus-js-client#306] opened 2021-12-30 14:11 UTC
Hi!, I am using the vimeo video upload client, which uses Tus and works on top of an Http service created with Node.js. For security reasons I should not expose sensitive information, such as access tokens, client secret and the client id.

The problem is that to be able to load a video I have to previously store them, this is not very performant and tedious.

Is there a possibility that a direct stream can be made using Tus?

**Comment by Acconut** [comment] 2021-12-30 16:14
Yes, tus-js-client supports uploading `Readable` streams directly. See the documentation: https://github.com/tus/tus-js-client/blob/master/docs/api.md#tusuploadfile-options

**Comment by 11ume** [comment] 2021-12-30 17:37
Thanks for your reply!, could you give me an minimal example of this feature?
Should I create a new stream **Readable** and then push the chunks?

**Comment by Acconut** [comment] 2021-12-30 19:23
The only example I have at hand is for uploading a file using a Readable stream: https://github.com/tus/tus-js-client/blob/master/demos/nodejs/index.js However, in your case it is sufficient to replace the call to `fs.createReadStream` with a call to wherever you are getting your video stream from.

> Should I create a new stream **Readable** and then push the chunks?

Yes, basically that is the way.

**Comment by 11ume** [comment] 2021-12-30 20:15
Thanks apparently it works!, only using http request object, that is a valid readable stream.

console.log(isReadableStream(req))
I have another query, how can I estimate the chunkSize in an optimal way?

Vimeo client method overloading
```js
Vimeo.prototype._performTusUpload = function(
  file,
  fileSize,
  attempt,
  completeCallback,
  progressCallback,
  errorCallback
) {

  let fileUpload = file
  if (typeof file === 'string') {
    fileUpload = fs.createReadStream(file)
  }

  // fileUpload is http request readable stream
  const upload = new tus.Upload(fileUpload, {
    endpoint: 'none',
    uploadSize: fileSize,
    chunkSize: 50000,
    retryDelays: [0, 1000, 3000, 5000],
    onError: errorCallback,
    onProgress: progressCallback,
    onSuccess: function () {
      return completeCallback(attempt.uri)
    }
  })

  upload.url = attempt.upload.upload_link
  upload.start()
}

```

**Comment by Acconut** [comment] 2022-01-01 20:05
Closing this issue since your question has been answered. Feel free to leave a comment if you want to continue the discussion :)

**Comment by 11ume** [comment] 2022-01-02 10:45
Thanks, it worked fine! I just had to pass it the http request to the tus instance, as this is a readable stream it works without problems. 

```js
  const CHUNK_SIZE = 5000000 // 5MB
  const upload = new tus.Upload(req, {
    endpoint: '',
    chunkSize: CHUNK_SIZE,
    uploadSize: size,
    retryDelays: [0, 1000, 3000, 5000],
    onError,
    onProgress,
    onSuccess: () => onSuccess(uri),
  })

  upload.url = uploadLink
  return upload
```

Now I have another problem but it has to do with the Fetch API (Browser).

I need to send the loading process to the browser, for this I am using fetch and ReadableStreams, but I have some problems, if I can solve them I could give you an cool example.

[fetch-upload-streaming](https://web.dev/fetch-upload-streaming)

**Comment by Acconut** [comment] 2022-01-05 20:48
> Thanks, it worked fine!

Glad to read that!

> I need to send the loading process to the browser, for this I am using fetch and ReadableStreams, but I have some problems,

Are these problem caused by tus-js-client? If not, I don´t think I can help much. I have never streamed data over the fetch API.

**Comment by Acconut** [comment] 2022-08-01 13:31
Closing this issue due to inactivity. Feel free to leave a comment if you want to continue the discussion :)

**Closed by Acconut** 2022-08-01 13:31 UTC
Labels: question
