### ISSUE TITLE
Uploading failed in React native ( IOS )

### ISSUE THREAD

**Issue by iqbalfaisal** [tus/tus-js-client#180] opened 2020-02-10 11:47 UTC
**Describe the bug**
APP is crashed during uploading in IOS.

**Setup details**
Please provide following details, if applicable to your situation:
- Runtime environment:  React Native
- Used tus-js-client version: ^1.8.0-2

![IMG-20200206-WA0000](https://user-images.githubusercontent.com/46706064/74147433-046d6300-4c25-11ea-927a-52b76ba067e8.jpg)

**Comment by Acconut** [comment] 2020-02-10 12:12
Is this a duplicate of https://github.com/tus/tus-js-client/issues/179#issuecomment-584089549?

**Closed** 2020-02-24 04:39 UTC
Labels: bug
