### ISSUE TITLE
How to cancel or abort uploading file. 

### ISSUE THREAD

**Issue by reoq22** [tus/tus-js-client#590] opened 2023-05-10 11:44 UTC
**Question**
I am using the following js code to upload a file, I want to add a button to cancel or abort file uploading does tus-js-client has any thing to do that? 

```
input.addEventListener('change', function (e) {
   
  var file = e.target.files[0]

  
  var upload = new tus.Upload(file, {
    endpoint: 'https://MyEndpoint:1080/files/',
    retryDelays: [0, 3000, 5000, 10000, 20000],
    metadata: {
      filename: file.name,
      filetype: file.type,
    },
    onError: function (error) {
      console.log('Failed because: ' + error)
    },
    onProgress: function (bytesUploaded, bytesTotal) {
      var percentage = ((bytesUploaded / bytesTotal) * 100).toFixed(2)
      console.log(bytesUploaded, bytesTotal, percentage + '%')
    },
    onSuccess: function () {
      console.log('Download %s from %s', upload.file.name, upload.url)
    },
  })

  
  upload.findPreviousUploads().then(function (previousUploads) {
    
    if (previousUploads.length) {
      upload.resumeFromPreviousUpload(previousUploads[0])
    }

   
    upload.start()
  })
})
```

**Comment by Acconut** [comment] 2023-05-10 12:20
You can use the abort method: https://github.com/tus/tus-js-client/blob/main/docs/api.md#tusuploadabortshouldterminate

**Comment by js-j** [comment] 2023-06-07 11:25
I have the following issue with the abort method:
If the upload is brand new, calling the abort method works as expected, and immediately stops the upload and corresponding PATCH request.
However, if it is resume(d)FromPreviousUpload, the following happens: the first call to abort() does not cancel the ongoing PATCH request, it seems to only set the _aborted flag for subsequent PATCH requests. Any further calls to abort() after the first one work as expected and do cancel the current PATCH request. So in effect the user has to wait for the PATCH request to finish to experience the pausing. This is especially problematic with a large or unrestrained chunkSize.

**Comment by Acconut** [comment] 2023-06-07 12:37
@js-j Please open a separate issue with your problem and please provide a small example to reproduce this behavior.

I am going to close this since the original question is already answered.

**Closed by Acconut** 2023-06-07 12:37 UTC
Labels: question

**Comment by js-j** [comment] 2023-06-07 17:18
My fault. Problem was my code called upload.start() twice. Thanks for taking the time to address this issue.
