### ISSUE TITLE
Terminate method doesnt execute options method onBeforeRequest

### ISSUE THREAD

**Issue by walterdavalos** [tus/tus-js-client#209] opened 2020-07-15 14:16 UTC
**Describe the bug**
When I invoke the method upload.abort(true) i noticed a DELETE request that did not send the parameters that I specified in the options method onBeforeRequest.

**To Reproduce**
1. Set for example onBeforeRequest to add a custom header
2. Start upload 
3. Abort upload with parameter shoultTerminate set true: upload.abort(true)
4. Check if the request has the custom header

**Setup details**
- Runtime environment: Node.js
- Used tus-js-client version: 2.1.1

**Comment by Acconut** [comment] 2020-07-15 14:19
Yes, you are right, this is missing. The problem is that the request handlers are not invoked, in the terminating function:

https://github.com/tus/tus-js-client/blob/2cad02ad6650a1b0aa231c4c3aa8829a8b742499/lib/upload.js#L118

Would you be willing to open a PR for this?

**Comment by bedgerotto** [comment] 2020-08-21 08:32
I created a [PR](https://github.com/tus/tus-js-client/pull/216) changing the terminate method to call onBeforeRequest and onAfterResponse from options, as it happens in the private method [_sendRequest.](https://github.com/tus/tus-js-client/blob/ffe21e2842fd243297fd3aba194c8d920170277d/lib/upload.js#L845) Hope it can be helpfull

**Comment by Acconut** [comment] 2020-09-01 06:14
Fixed in #216.

**Closed by Acconut** 2020-09-01 06:14 UTC
Labels: bug
