### ISSUE TITLE
Uploads with size 0 bytes won't work

### ISSUE THREAD

**Issue by fentas** [tus/tus-js-client#106] opened 2018-03-25 16:06 UTC
Using version `"tus-js-client": "^1.4.5"`

**Some information**

_tus-js-client_
```
{ chunkSize: 16384,
  endpoint: 'http://tusd:1080/files/',
  retryDelays: [ 0, 1000, 3000, 5000 ],
  metadata: 
  { name: 'ttest',
    authorization: '**',
    directoryId: '**' },
  onError: [AsyncFunction: onError],
  uploadSize: 0,
  onSuccess: [AsyncFunction: onSuccess] }
```

_tusd_
```
[tusd] event="UploadCreated" id="b646a2d6f130e9360442ffa11bc8ec28" size="0" url="http://tusd:1080/files/b646a2d6f130e9360442ffa11bc8ec28" 
[tusd] event="ResponseOutgoing" status="201" method="POST" path="" 
[tusd] event="RequestIncoming" method="HEAD" path="b646a2d6f130e9360442ffa11bc8ec28" 
[tusd] event="ResponseOutgoing" status="200" method="HEAD" path="b646a2d6f130e9360442ffa11bc8ec28" 
```
Missing `UploadFinished`, `HookInvocationStart` and `HookInvocationFinish`.

Maybe this is an issue of `tusd`?

**Edit:** tusd should be able to handle 0 byte files.
> The Upload-Length request and response header indicates the size of the entire upload in bytes. The value MUST be a non-negative integer.
https://tus.io/protocols/resumable-upload.html#upload-length

**Comment by Acconut** [comment] 2018-03-28 19:52
What exactly is not working? If only the upload-finished hook is not invoked, then this issue is entirely related to tusd. I assume that tusd is able to handle empty uploads but the upload-finished hook is not invoked by a missing check.

**Comment by fentas** [comment] 2018-03-29 11:31
Hm. Firstly the `onSuccess` is not fired and nothing is happening.
I guess tusd is waiting for a `PATCH` request but only got a `POST`.

I am not sure if tus specs require a `PATCH` request to finish an upload?

**Comment by Acconut** [comment] 2018-03-29 12:45
> I am not sure if tus specs require a PATCH request to finish an upload?

No, the specification does not need a PATCH request. If you have an empty upload, it's enough to just send the POST request.

> I guess tusd is waiting for a PATCH request but only got a HEAD/POST.

There was a missing check in tusd, which did not fire the post-finish hook for empty uploads but that is fixed in https://github.com/tus/tusd/commit/c470fe3a9dfbc40b74aed9518138993df2fc3240.

>  Firstly the onSuccess is not fired

This looks like a direct issue in tus-js-client. I will investigate.

**Comment by Acconut** [comment] 2018-03-29 13:47
> Firstly the onSuccess is not fired

I was not able to reproduce this error. When I test using the demo at https://rawgit.com/tus/tus-js-client/master/demo/index.html, the onSuccess callback is called as intended.

**Comment by fentas** [comment] 2018-04-03 15:04
I'd tried to figure out why `onSuccess` is not firing for me.
First of all, I am using a `PassThrough` stream as file.

- It goes into `_createUpload#L277` which is successfully called. As `upload_size` is equal to `0` _tus\_node\_server_ will directly finish the upload (cleaning up - moving the file) ~ returning `201` and `Location` header.
- It goes on to `_startUpload#404` and calls `xhr.send(<empty buffer>)#492` (`PATCH` request) which will never send the request, replacing it with `null` it will send the request but as the upload is already finished it will fail as the file is not there anymore. 

If we assume that `POST` will finish the request on 0 bytes files we should check the file size and finish it without calling `_startUpload`.

**Closed** 2018-04-06 08:46 UTC

**Comment by Acconut** [comment] 2018-04-06 08:48
Thank you very much for your investigation and patch :+1:
