### ISSUE TITLE
The value of "start" is out of range. It must be <= "end". Received

### ISSUE THREAD

**Issue by vipuls8131** [tus/tus-js-client#145] opened 2019-03-12 12:51 UTC
I am trying to upload file from Upppy tusd, But when I am start the uploading its giving me this error.

internal/fs/streams.js:69
      throw new ERR_OUT_OF_RANGE('start', '<= "end"', errVal);
      ^

RangeError [ERR_OUT_OF_RANGE]: The value of "start" is out of range. It must be <= "end". Received {start: 32768, end: 32767}
    at ReadStream (internal/fs/streams.js:69:13)
    at new ReadStream (/home/ubuntu/uppywithcompanian/node_modules/graceful-fs/graceful-fs.js:195:28)
    at createReadStream (fs.js:1716:10)
    at FileSource.slice (/home/ubuntu/uppywithcompanian/node_modules/tus-js-client/lib.es5/node/source.js:54:45)
    at Upload._startUpload (/home/ubuntu/uppywithcompanian/node_modules/tus-js-client/lib.es5/upload.js:599:22)
    at Request.xhr.onload (/home/ubuntu/uppywithcompanian/node_modules/tus-js-client/lib.es5/upload.js:544:16)
    at ClientRequest.<anonymous> (/home/ubuntu/uppywithcompanian/node_modules/tus-js-client/lib.es5/node/request.js:88:15)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uppy-with-companion-example@1.0.0 server: `node ./server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uppy-with-companion-example@1.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2019-03-12T12_10_43_094Z-debug.log

**Comment by Acconut** [comment] 2019-03-12 19:08
Thank you for reporting this problem. Can you provide is with a minimal example to reproduce this problem? Otherwise it's nearly impossible for us to debug this.

**Comment by vipuls8131** [comment] 2019-03-13 04:54
Thanks for your quick reply,
Here if I calling server API from localhost then its working fine but when I'm going to working on server(client and server files are on same host) that time its giving me above error.Following are the index.html(client) and index.js files(server)
----------------------------------------------------------------------
tus commands:
tusd --dir ./myuploads
tusd -hooks-http http://my-server-host.com:3020/uppyresponse
------------------------------------------------------------------
index.html

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title></title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://transloadit.edgly.net/releases/uppy/v0.30.3/uppy.min.css" rel="stylesheet">
  </head>
  <body>
    <button id="uppyModalOpener">Open Modal</button>
    <script src="https://transloadit.edgly.net/releases/uppy/v0.30.3/uppy.min.js"></script>
    <script>
      const uppy = Uppy.Core({debug: true, autoProceed: false})
        .use(Uppy.Dashboard, { trigger: '#uppyModalOpener' })
        .use(Uppy.Instagram, { target: Uppy.Dashboard, serverUrl: 'http://localhost:3020' })
        .use(Uppy.GoogleDrive, { target: Uppy.Dashboard, serverUrl: 'http://localhost:3020' })
        .use(Uppy.Url,{target:Uppy.Dashboard,serverUrl:"http://localhost:3020",locale:{}})
        .use(Uppy.Tus, { endpoint: 'http://localhost:1080/files/' })
      uppy.setMeta({uploadId:"123", userId:"VIP234", userName:"test"});
      uppy.on('success', (fileCount) => {
        console.log(`${fileCount} files uploaded`)
      })
    </script>
  </body>
</html>
```
--------------------------------------------------------------

index.js(server)

```
const express = require('express')
const companion = require('@uppy/companion')
const bodyParser = require('body-parser')
const session = require('express-session');
const path = require('path');
var multer  = require('multer');
const app = express();

app.use(bodyParser.json({limit: '50mb',
extended: true}));
app.use(session({
  secret: 'some-secret',
  resave: true,
  saveUninitialized: true
}));

var storage = multer.diskStorage({
  destination: function (req, file, cb) {
    cb(null, '../myuploads')
  },
  filename: function (req, file, cb) {
    cb(null, file.fieldname)
  }
});

var upload = multer({ storage: storage });

app.use((req, res, next) => {
  res.setHeader('Access-Control-Allow-Origin', req.headers.origin || '*')
  res.setHeader(
    'Access-Control-Allow-Methods',
    'GET, POST, OPTIONS, PUT, PATCH, DELETE'
  )
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Authorization, Origin, Content-Type, Accept'
  )
  res.setHeader('Access-Control-Allow-Credentials', 'true')
  next()
});

// Routes
app.get('/uppywithcompanians', (req, res) => {
 res.sendFile(path.join(__dirname + '../../client/index.html'));
});

app.post('/uppyresponse', upload.any(), (req, resp, next) => {
  console.log("req.body: ", req.body);
  resp.status(200).json({status:true});
});

// initialize uppy
const uppyOptions = {
  providerOptions: {
    google: {
      key: 'your google key',
      secret: 'your google secret'
    },
    instagram: {
      key: 'your instagram key',
      secret: 'your instagram secret'
    }
    // you can also add options for dropbox here
  },
  server: {
    host: 'localhost:3020',
    protocol: 'http'
  },
  filePath: './output',
  secret: 'some-secret',
  debug: true
}

app.use(companion.app(uppyOptions))

// handle 404
app.use((req, res, next) => {
  return res.status(404).json({ message: 'Not Found' })
})

// handle server errors
app.use((err, req, res, next) => {
  console.error('\x1b[31m', err.stack, '\x1b[0m')
  res.status(err.status || 500).json({ message: err.message, error: err })
})

companion.socket(app.listen(3020), uppyOptions)

console.log('Welcome to Companion!')
console.log(`Listening on http://0.0.0.0:${3020}`)
```

**Comment by Acconut** [comment] 2019-03-15 21:32
Is this happening for every upload you perform using Uppy or just if you use the Google Drive/Instagram/URL plugin? Also what do you mean by "This is happen when uploading is faster than downloading"? Is your uplink speed greater than your downlink speed?

@ifedapoolarewaju Could this be related to your recent PR to tus-js-client for adding Node.js streams support? It seems to be happening inside Companion, so it would be nice if you could have a look.

**Comment by ifedapoolarewaju** [comment] 2019-03-17 21:25
this issue is a companion issue. It has to do with the old way tus uploads are managed on companion which has begun to break since recent changes made in tus-js-client [1.6](https://github.com/tus/tus-js-client/commit/e628772a71ec48001a43340c6556133e4e5631e2).

My [PR on uppy](https://github.com/transloadit/uppy/pull/1274) fixes this issue, but it also depends on [this PR](https://github.com/tus/tus-js-client/pull/140) on tus-js-client

**Comment by Acconut** [comment] 2019-03-18 21:47
@ifedapoolarewaju Thanks for looking into this. How did tus-js-client 1.6 break your application? I am seriously concerned as I am not aware of any such problems and a minor release should not introduce breaking changes. I would love to read what you are referring to.

Also, I had another look at your tus-js-client PR right now.

**Comment by vipuls8131** [comment] 2019-03-20 09:36
@Acconut This issue happens when i am using url plugin. Generally for small files this issue is not seen, but when i try large file 100mb+ i see this issue.

**Comment by ifedapoolarewaju** [comment] 2019-03-20 14:24
@Acconut it is probably related to [this change](https://github.com/tus/tus-js-client/commit/ae4369cce08505d8df77c339e7cf2179693ae9cd). During tus uploads, uppy [consistently updates the chunkSize](https://github.com/transloadit/uppy/blob/master/packages/%40uppy/companion/src/server/Uploader.js#L281) to match the bytes available for upload so far. In the case where chunkSize temporarily evaluates to `0`, this error may be triggered.

**Comment by Acconut** [comment] 2019-03-21 19:17
> @ifedapoolarewaju it is probably related to this change. During tus uploads, uppy consistently updates the chunkSize to match the bytes available for upload so far.

This sounds like a very bad idea. Why are you modifying the options while tus-js-client is running? The API does not (yet) forbid it but no portions of the code consider modifications for the options.

> In the case where chunkSize temporarily evaluates to 0, this error may be triggered.

Ok, but this sounds like the problem is caused by Uppy because it sets chunkSize to 0. Or do I misunderstand something?

Also, is there a workaround for @vipuls8131 while your PR is pending and Uppy is updated?

**Comment by Acconut** [comment] 2019-04-05 20:13
@ifedapoolarewaju Is this problem resolved now that https://github.com/transloadit/uppy/pull/1274 is merged?

**Comment by ifedapoolarewaju** [comment] 2019-04-05 20:55
Yes it is

**Comment by Acconut** [comment] 2019-04-09 20:07
@ifedapoolarewaju That's great to hear! Would you mind commenting on my question from above about the questionable behavior from Uppy?

> This sounds like a very bad idea. Why are you modifying the options while tus-js-client is running? The API does not (yet) forbid it but no portions of the code consider modifications for the options.

@vipuls8131 I am going to close this issue. Please upgrade to the (latest?) Uppy/Companion version to fix your problem.

**Closed by Acconut** 2019-04-09 20:07 UTC

**Comment by ifedapoolarewaju** [comment] 2019-04-09 20:14
@Acconut I didn't answer because it is no longer relevant with the changes here https://github.com/transloadit/uppy/pull/1274 but the reason we were updating the chunkSize on the fly in the past was in order to accommodate for parallel `download -> upload`. So the `chunkSize` is continuously updated to the value of the `bytes downloaded - bytes already uploaded by tus`.

But like I said, this is not relevant anymore, as the behaviour is no longer the same

**Comment by Acconut** [comment] 2019-04-09 20:42
Ok, that's nice to hear.

> I didn't answer because it is no longer relevant

In that case it would have been nice if you had said that directly :)
