### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>' (mix require and export)

### ISSUE THREAD

**Issue by figitaki** [tus/tus-js-client#71] opened 2017-05-09 19:34 UTC
I'm getting this error when importing this module in a project that uses webpack and babel. I'm using the following babel config to enable webpack's tree shaking.

```js
// .babelrc
{
  "presets": [
    [
      "latest",
      {
        "es2015": {
          "modules": false
        }
      }
    ],
    "react",
    "stage-0"
  ]
}
```

This causes an error when I import the module (webpack/webpack#4039) since the `lib/index.js` mixes `import` with `module.exports`. As a workaround I simply import the `lib.es5/index` to force babel to transpile the entire source code.

```js
import tus from 'tus-js-client/lib.es5'

/* ... */
```

But a better fix would be to not mix the two module formats.

**Comment by Acconut** [comment] 2017-05-15 20:08
I am not able to reproduce your issues. Could you please also include the necessary sections from your Webpack configuration? Also, which versions of babel and webpack are you using?

**Comment by Acconut** [comment] 2017-10-23 15:57
Closing this issue due to a lack of information. Feel free to leave a comment if you want to continue the discussion :)

**Closed by Acconut** 2017-10-23 15:57 UTC

**Comment by ChristianDavis** [comment] 2018-03-19 17:29
I ran into same issue, code is incorrect https://github.com/tus/tus-js-client/pull/103
